# Config File for Cool Penguin Snowball

[Player_1]
turnedOn = true
controlScheme = CONTROL_SCHEME_KEYBOARD_1

[Player_2]
turnedOn = true
controlScheme = CONTROL_SCHEME_KEYBOARD_2

[Player_3]
turnedOn = true
controlScheme = CONTROL_SCHEME_CONTROLLER_1

[Player_4]
turnedOn = true
controlScheme = CONTROL_SCHEME_CONTROLLER_2

[Keyboard_1]
start = KEY_CODE_SPACE
pause = KEY_CODE_ENTER
quit = KEY_CODE_ESCAPE
left = KEY_CODE_A
right = KEY_CODE_D
up = KEY_CODE_W
down = KEY_CODE_S
grab = KEY_CODE_SPACE
throw = KEY_CODE_RIGHT_ALT

[Keyboard_2]
start = KEY_CODE_KP_0
pause = KEY_CODE_KP_ENTER
quit = KEY_CODE_KP_SUBTRACT
left = KEY_CODE_LEFT
right = KEY_CODE_RIGHT
up = KEY_CODE_UP
down = KEY_CODE_DOWN
grab = KEY_CODE_KP_0
throw = KEY_CODE_KP_DECIMAL

[Controller_1]
start = 0
pause = 7
quit = 1
left = 13
right = 11
up = 10
down = 12
grab = 0
throw = 5
moveRightLeftAxis = 0
moveDownUpAxis = 1
axisDeadzone = 0.2

[Controller_2]
start = 0
pause = 7
quit = 1
left = 13
right = 11
up = 10
down = 12
grab = 0
throw = 5
moveRightLeftAxis = 0
moveDownUpAxis = 1
axisDeadzone = 0.2

[Controller_3]
start = 0
pause = 7
quit = 1
left = 13
right = 11
up = 10
down = 12
grab = 0
throw = 5
moveRightLeftAxis = 0
moveDownUpAxis = 1
axisDeadzone = 0.2

[Controller_4]
start = 0
pause = 7
quit = 1
left = 13
right = 11
up = 10
down = 12
grab = 0
throw = 5
moveRightLeftAxis = 0
moveDownUpAxis = 1
axisDeadzone = 0.2

[Game_Constants]

randomNumberSeed = 777

# Values:
# ------------------------------------------------------------------------------
# Control Schemes:
#
# CONTROL_SCHEME_KEYBOARD_1
# CONTROL_SCHEME_KEYBOARD_2
# CONTROL_SCHEME_CONTROLLER_1
# CONTROL_SCHEME_CONTROLLER_2
# CONTROL_SCHEME_CONTROLLER_3
# CONTROL_SCHEME_CONTROLLER_4
#
# Keyboard Button Values:
# 
# KEY_CODE_SPACE
# KEY_CODE_APOSTROPHE
# KEY_CODE_COMMA
# KEY_CODE_MINUS
# KEY_CODE_PERIOD
# KEY_CODE_SLASH
# KEY_CODE_0
# KEY_CODE_1 
# KEY_CODE_2 
# KEY_CODE_3 
# KEY_CODE_4 
# KEY_CODE_5 
# KEY_CODE_6 
# KEY_CODE_7 
# KEY_CODE_8 
# KEY_CODE_9 
# KEY_CODE_SEMICOLON
# KEY_CODE_EQUAL
# KEY_CODE_A
# KEY_CODE_B
# KEY_CODE_C
# KEY_CODE_D
# KEY_CODE_E
# KEY_CODE_F
# KEY_CODE_G
# KEY_CODE_H
# KEY_CODE_I
# KEY_CODE_J
# KEY_CODE_K
# KEY_CODE_L
# KEY_CODE_M
# KEY_CODE_N
# KEY_CODE_O
# KEY_CODE_P
# KEY_CODE_Q
# KEY_CODE_R
# KEY_CODE_S
# KEY_CODE_T
# KEY_CODE_U
# KEY_CODE_V
# KEY_CODE_W
# KEY_CODE_X
# KEY_CODE_Y
# KEY_CODE_Z
# KEY_CODE_LEFT_BRACKET
# KEY_CODE_BACKSLASH
# KEY_CODE_RIGHT_BRACKET
# KEY_CODE_GRAVE_ACCENT
# KEY_CODE_WORLD_1
# KEY_CODE_WORLD_2
# KEY_CODE_ESCAPE
# KEY_CODE_ENTER
# KEY_CODE_TAB
# KEY_CODE_BACKSPACE
# KEY_CODE_INSERT
# KEY_CODE_DELETE
# KEY_CODE_RIGHT
# KEY_CODE_LEFT
# KEY_CODE_DOWN
# KEY_CODE_UP
# KEY_CODE_PAGE_UP
# KEY_CODE_PAGE_DOWN
# KEY_CODE_HOME
# KEY_CODE_END
# KEY_CODE_CAPS_LOCK
# KEY_CODE_SCROLL_LOCK
# KEY_CODE_NUM_LOCK
# KEY_CODE_PRINT_SCREEN
# KEY_CODE_PAUSE
# KEY_CODE_F1
# KEY_CODE_F2
# KEY_CODE_F3
# KEY_CODE_F4
# KEY_CODE_F5
# KEY_CODE_F6
# KEY_CODE_F7
# KEY_CODE_F8
# KEY_CODE_F9
# KEY_CODE_F10
# KEY_CODE_F11
# KEY_CODE_F12
# KEY_CODE_F13
# KEY_CODE_F14
# KEY_CODE_F15
# KEY_CODE_F16
# KEY_CODE_F17
# KEY_CODE_F18
# KEY_CODE_F19
# KEY_CODE_F20
# KEY_CODE_F21
# KEY_CODE_F22
# KEY_CODE_F23
# KEY_CODE_F24
# KEY_CODE_F25
# KEY_CODE_KP_0
# KEY_CODE_KP_1
# KEY_CODE_KP_2
# KEY_CODE_KP_3
# KEY_CODE_KP_4
# KEY_CODE_KP_5
# KEY_CODE_KP_6
# KEY_CODE_KP_7
# KEY_CODE_KP_8
# KEY_CODE_KP_9
# KEY_CODE_KP_DECIMAL
# KEY_CODE_KP_DIVIDE
# KEY_CODE_KP_MULTIPLY
# KEY_CODE_KP_SUBTRACT
# KEY_CODE_KP_ADD
# KEY_CODE_KP_ENTER
# KEY_CODE_KP_EQUAL
# KEY_CODE_LEFT_SHIFT
# KEY_CODE_LEFT_CONTROL
# KEY_CODE_LEFT_ALT
# KEY_CODE_LEFT_SUPER
# KEY_CODE_RIGHT_SHIFT
# KEY_CODE_RIGHT_CONTROL
# KEY_CODE_RIGHT_ALT
# KEY_CODE_RIGHT_SUPER
# KEY_CODE_MENU
#
# Controller Button & Axis Indices (X-Box Controller):
#
# Button Index 0 = A Button
# Button Index 1 = B Button
# Button Index 2 = X Button
# Button Index 3 = Y Button
# Button Index 4 = L Button
# Button Index 5 = R Button
# Button Index 6 = View Button
# Button Index 7 = Menu Button
# Button Index 8 = Left Stick Depress
# Button Index 9 = Right Stick Depress
# Button Index 10 = D-Pad Up
# Button Index 11 = D-Pad Right
# Button Index 12 = D-Pad Down
# Button Index 13 = D-Pad Left
#
# Axis Index 0 = Left Stick Right (+) & Left (-)
# Axis Index 1 = Left Stick Down (+) & Up (-)
# Axis Index 2 = Right Stick Right (+) & Left (-)
# Axis Index 3 = Right Stick Down (+) & Up (-)
# Axis Index 4 = Left Trigger Down (+) & Up (-)
# Axis Index 5 = Right Trigger Down (+) & Up (-)