@REM This script calls the glslc compiler to individually compile
@REM each shader file in the given directory.
@REM
@REM Supported file extensions are as follows:
@REM
@REM .vert - a vertex shader
@REM .tesc - a tessellation control shader
@REM .tese - a tessellation evaluation shader
@REM .geom - a geometry shader
@REM .frag - a fragment shader
@REM .comp - a compute shader
@REM
@REM First parameter is the compiler (it's sort of optional)
@REM * By default it'll be set by reading in the value from the glslc_path.txt
@REM   generated by the CMake script.
@REM
@REM Second parameter is the shader directory (it's optional)
@REM * By default it's ..\Shaders
@REM
@REM Third parameter is the output directory (it's optional)
@REM * By default it's the input directory

@ECHO OFF

SETLOCAL

SET compiler=%~1

IF "%~1"=="" (
    @REM ECHO ERROR: provide glslc path as parameter
    @REM GOTO :EOF
    IF EXIST glslc_path.txt (
        SET /p compiler=<glslc_path.txt
    )
)

SET input_directory=%~2

IF "%~2"=="" (
    @REM ECHO ERROR: provide shader directory
    @REM GOTO :EOF
    SET input_directory=..\Shaders
)

SET output_directory=%~3

IF "%~3"=="" (
    @REM ECHO ERROR: provide shader directory
    @REM GOTO :EOF
    SET output_directory=%input_directory%
)

IF NOT "%~4"=="" (
    ECHO ERROR: too many parameters
    GOTO :EOF
)

IF NOT EXIST %compiler% (
    ECHO ERROR: glslc doesn't exist
    GOTO :EOF
)

IF NOT EXIST "%input_directory%\" (
    ECHO ERROR: input directory doesn't exist
    GOTO :EOF
)

IF NOT EXIST "%output_directory%\" (
    ECHO ERROR: output directory doesn't exist
    GOTO :EOF
)

SETLOCAL ENABLEDELAYEDEXPANSION

FOR %%G IN (
    "%input_directory%\*.vert"
    "%input_directory%\*.tesc"
    "%input_directory%\*.tese"
    "%input_directory%\*.geom"
    "%input_directory%\*.frag"
    "%input_directory%\*.comp"
) DO (
    SET file_name=%%~nG
    SET file_extension=%%~xG
    %compiler% "%%G" -o "%output_directory%\!file_name!_!file_extension:~1!.spv"
    ECHO input:  "%%G"
    ECHO output: "%output_directory%\!file_name!_!file_extension:~1!.spv"
)

ENDLOCAL

@REM PAUSE