@REM This script calls the file to header converter program to individually
@REM convert each shader file into a cpp header file, in the given directory.
@REM The header will contain a array of binary data.
@REM
@REM Supported file extensions are as follows:
@REM
@REM .spv - SPIR-V (Standard Portable Intermediate Representation - Virtual)
@REM
@REM First parameter is the converter program (it's sort of optional)
@REM * By default it'll be set by reading in the value from the
@REM   fileToHeaderConverter_path.txt generated by the CMake script.
@REM
@REM Second parameter is the shader directory (it's optional)
@REM * By default it's ..\Shaders
@REM
@REM Thrid parameter is the output directory (it's optional)
@REM * By default it's the input directory

@ECHO OFF

SETLOCAL

SET converter=%~1

IF "%~1"=="" (
    @REM ECHO ERROR: provide converter path as parameter
    @REM GOTO :EOF
    IF EXIST fileToHeaderConverter_path.txt (
        SET /p converter=<FileToHeaderConverter_path.txt
    )
)

SET input_directory=%~2

IF "%~2"=="" (
    @REM ECHO ERROR: provide shader directory
    @REM GOTO :EOF
    SET input_directory=..\Shaders
)

SET output_directory=%~3

IF "%~3"=="" (
    @REM ECHO ERROR: provide shader directory
    @REM GOTO :EOF
    SET output_directory=%input_directory%
)

IF NOT "%~4"=="" (
    ECHO ERROR: too many parameters
    GOTO :EOF
)

IF NOT EXIST %converter% (
    ECHO ERROR: glslc doesn't exist
    GOTO :EOF
)

IF NOT EXIST "%input_directory%\" (
    ECHO ERROR: input directory doesn't exist
    GOTO :EOF
)

IF NOT EXIST "%output_directory%\" (
    ECHO ERROR: output directory doesn't exist
    GOTO :EOF
)

SETLOCAL ENABLEDELAYEDEXPANSION

FOR %%G IN (
    "%input_directory%\*.spv"
) DO (
    SET file_name=%%~nG
    SET file_extension=%%~xG
    "%converter%" "%%G" "%output_directory%\!file_name!_!file_extension:~1!.h" "g_!file_name!_!file_extension:~1!"
    ECHO input:  "%%G"
    ECHO output: "%output_directory%\!file_name!_!file_extension:~1!.h"
)

ENDLOCAL

@REM PAUSE